always return status if success

diff --git a/api/commit-reply b/api/commit-reply
--- a/api/commit-reply
+++ b/api/commit-reply
@@ -9,25 +9,28 @@ source "$(dirname "${BASH_SOURCE[0]}")/tools/common"
 url="$GET_url$POST_url"
 email="$GET_email$POST_email"
 password="$GET_password$POST_password"
+id="$GET_id$POST_id"
 
 [[ "$email" != "" ]] && { ./tools/auth "$email" "$password" || exit 1; }
 
 db_top="$(busybox realpath "$(dirname "${BASH_SOURCE[0]}")/../db")"
 accounts_top="$db_top/accounts"
 article_dir="$db_top/articles/$url/_content"
+reply_dir="$db_top/articles/$url/comments/$id"
 
-[[ "$url" == "" ]] && { echo 'no url specified'; exit 1; }
-[[ ! -d "$article_dir" ]] && { echo 'url folder not found'; exit 1; }
+[[ "$url" == "" ]] && { echo 'url not specified'; exit 1; }
+[[ ! -d "$reply_dir" ]] && { echo 'reply folder not found'; exit 1; }
 
 #default "dflt" if no email specified
 permissions=$(git config --file="$accounts_top/$email" base.permissions || echo "dflt")
 attributes=$(git config --file="$article_dir/metadata" base.attributes)
 check_attribute_overlap "$permissions" "$attributes" || { echo 'permission denied'; exit 1; }
 
-echo -n '{"article":'
-./tools/json-article "$url" true
-echo ','
-echo '"status":"success"}'
+#if new reply
+if [[ "$id" == "" ]]; then
+ #id=max+1
+fi
+
 exit 0
 
 %>
diff --git a/api/read-replys b/api/read-replys
--- a/api/read-replys
+++ b/api/read-replys
@@ -4,12 +4,13 @@ Content-Type: application/json
 <%
 
 set -e
+source "$(dirname "${BASH_SOURCE[0]}")/tools/common"
 
-url="$GET_url"
-email="$GET_email"
-password="$GET_password"
-start="$GET_start"
-count="$GET_count"
+url="$GET_url$POST_url"
+email="$GET_email$POST_email"
+password="$GET_password$POST_password"
+start="$GET_start$POST_start"
+count="$GET_count$POST_count"
 
 [[ "$email" != "" ]] && { ./tools/auth "$email" "$password" || exit 1; }
 
@@ -23,22 +24,13 @@ accounts_top="$db_top/accounts"
 article_dir="$db_top/articles/$url/_content"
 reply_top="$db_top/articles/$url/comments"
 
-[[ "$url" == "" ]] && { echo '{"error":"no url specified"}'; exit 1; }
-[[ ! -d "$reply_top" ]] && { echo '{"error":"reply folder not found"}'; exit 1; }
+[[ "$url" == "" ]] && { echo 'no url specified'; exit 1; }
+[[ ! -d "$reply_top" ]] && { echo 'reply folder not found'; exit 1; }
 
+#default "dflt" if no email specified
 permissions=$(git config --file="$accounts_top/$email" base.permissions || echo "dflt")
-permissions=(${permissions//,/ })
-
 attributes=$(git config --file="$article_dir/metadata" base.attributes)
-
-have_permission="false"
-
-for i in "${!permissions[@]}"; do
-  p="P_${permissions[i]}"
-  [[ "$attributes" =~ "$p" ]] && { have_permission="true"; break; }
-done
-
-[[ "$have_permission" != "true" ]] && { echo '{"error":"permission denide"}'; exit 1; }
+check_attribute_overlap "$permissions" "$attributes" || { echo 'permission denied'; exit 1; }
 
 total="$(ls -1 $reply_top | wc -l)"
 ((start > total)) && start=$((total))
@@ -46,14 +38,13 @@ total="$(ls -1 $reply_top | wc -l)"
 
 index=($(ls "$reply_top" | head -n $((start+count)) | tail -n $count))
 
-echo -n "["
+echo -n '{"replys":['
 for i in "${!index[@]}"; do
   ./tools/json-reply "$url" "${index[i]}"
   [[ $((i+1)) != ${#index[@]} ]] && echo ","
 done
-echo "]"
-
+echo '],'
+echo '"status":"success"}'
 exit 0
 
 %>
-
diff --git a/api/tools/json-article b/api/tools/json-article
--- a/api/tools/json-article
+++ b/api/tools/json-article
@@ -1,8 +1,7 @@
 #!/bin/bash
 
-source "$(dirname "${BASH_SOURCE[0]}")/common"
-
 set -e
+source "$(dirname "${BASH_SOURCE[0]}")/common"
 
 url="$1"       # url name
 show_body="$2" # true or not
@@ -10,8 +9,8 @@ show_body="$2" # true or not
 db_top="$(busybox realpath "$(dirname "${BASH_SOURCE[0]}")/../../db")"
 article_dir="$db_top/articles/$url/_content"
 
-[[ "$url" == "" ]] && { echo '{"error":"no url specified"}'; exit 1; }
-[[ ! -d "$article_dir" ]] && { echo '{"error":"url folder not found"}'; exit 1; }
+[[ "$url" == "" ]] && { echo 'no url specified'; exit 1; }
+[[ ! -d "$article_dir" ]] && { echo 'url folder not found'; exit 1; }
 
 title=$(git config --file="$article_dir/metadata" base.title)
 date=$(git config --file="$article_dir/metadata" base.date)
@@ -36,4 +35,3 @@ else
 fi
 
 exit 0
-
diff --git a/api/tools/json-reply b/api/tools/json-reply
--- a/api/tools/json-reply
+++ b/api/tools/json-reply
@@ -1,8 +1,7 @@
 #!/bin/bash
 
-source "$(dirname "${BASH_SOURCE[0]}")/common"
-
 set -e
+source "$(dirname "${BASH_SOURCE[0]}")/common"
 
 url="$1"       # url name
 id="$2"        # reply id
@@ -13,9 +12,9 @@ article_dir="$db_top/articles/$url/_content"
 reply_top="$db_top/articles/$url/comments"
 reply_dir="$reply_top/$id/_content"
 
-[[ "$url" == "" ]] && { echo '{"error":"no url specified"}'; exit 1; }
-[[ ! -d "$article_dir" ]] && { echo '{"error":"url folder not found"}'; exit 1; }
-[[ ! -d "$reply_dir" ]] && { echo '{"error":"reply folder not found"}'; exit 1; }
+[[ "$url" == "" ]] && { echo 'no url specified'; exit 1; }
+[[ ! -d "$article_dir" ]] && { echo 'url folder not found'; exit 1; }
+[[ ! -d "$reply_dir" ]] && { echo 'reply folder not found'; exit 1; }
 
 date=$(git config --file="$reply_dir/metadata" base.date)
 registered=$(git config --file="$reply_dir/metadata" base.registered)
@@ -36,4 +35,3 @@ echo    "\"format\":\"$format\","
 echo -n "\"body\":$(json_escape "$body")}"
 
 exit 0
-
