add write-reply

diff --git a/api/get-captcha b/api/get-captcha
--- a/api/get-captcha
+++ b/api/get-captcha
@@ -12,10 +12,11 @@ date=$(date --iso-8601=seconds)
 string=$(tr -dc A-Za-z0-9 2>/dev/null < /dev/urandom | head -c $captcha_length) #avoid stderr Broken pipe message
 [[ "${#string}" != "$captcha_length" ]] && exit 1
 
-base64_img=$(./tools/base64-captcha $string)
-string=${string,,} #to lowercase; ${string^^} for uppercase
+base64_img=$(./tools/base64-captcha $string) || { echo "build captcha img failed"; exit 1; }
+string=${string^^} #to uppercase; ${string,,} for lowercase
 
-touch ".cache/captcha/$date-$string" # restore by: ${filename%-*} and ${filename##*-}
+[[ ! -d ".cache/captcha" ]] && { mkdir -p ".cache/captcha" || { echo "create .cache/captcha failed"; exit 1; }; }
+touch ".cache/captcha/$date-$string" || { echo "create .cache/captcha/$date-$string failed"; exit 1; }
 
 echo "{\"date\":\"$date\","
 echo "\"image\":\"$base64_img\","
